### ISSUE TITLE
Access key for Sauce Labs is not working

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon#1013]
All the [last pull request builds](https://travis-ci.org/sinonjs/sinon/pull_requests) are failing the Sauce Labs tests with this error:

```
    Sauce Labs Authentication Error.
    You used username 'sinonjs' and access key 'None' to authenticate, which are not valid Sauce Labs credentials.
```

if you look at the output and compare it to a [passing lolex build running on SauceLabs](https://travis-ci.org/sinonjs/lolex/jobs/115327462) you can see that the `export SAUCE_ACCESS_KEY=[secure]` line is missing. I am guessing that the `secure` line is somehow corrupted in our `.travis.yml` file.

I am assigning this to you, @mantoni, as I was unable to fix it myself. I went to this [SauceLabs page](https://docs-staging.saucelabs.com/ci-integrations/travis-ci/#adding-credentials-for-a-public-github-repo) to generate secret credentials, and when entering `sinonjs/sinon` I just got
```
env:
  global:
    - secure: false
    - secure: false
```
Which is weird, because it worked for all other repos I tested (including `sinonjs/lolex`), which would produce something along the lines of:
```
env:
  global:
    - secure: P+4VUOA7/evZoQnu3oMyi1hb2zn80ydK+x6rIYRCAKgJKy9PpjOJj1LRh1HMksq05sSeGl5TXtG4mIst3E6Wa+ZFiv0CJSFTmnhyxydt7FJfxS7RR+8yJNdqYxiuYzXTb/d30OI8j1KVyMIJf0GXzT4503n5Hq/obnmzDZGCvb1I3u1Iz7hUTlwtKDuPtQKaQ8vCC82gW9ZkSMmVa7x8n9MF0JLdWR41ZDa2LBPRE2Tp9TOfVBovXEpZNgkDWMrtkdtdXrbUkdthga/JaM54ql61MXGbzkIu7cs+d+GDu4y/oxeHdBkZMcH2qZB61lNp6AEk/xeAwZbVSC8OqE6FMD6m2/pN/NH+3ld11uGX1cP0hHJu75W3Z+CX8MJvmroaBwOOGiVwgFKHDHNj8k1HSvEIW+SmU+7aVKkeOFHWcVUQroJXQdv5v30pWlo6EYuCFCrVx5Lp32FYfARrJSyga++R51zyAUCIsULTzJB7TNOTwHRFYMCwvei95dBzBmrnw9GsECDp0RgiZYXBJfLmu5Xr2pyd1it6btCGk2j5Pj06EwYYpAsWs1r1eauy2Zg2mCDKVbJSXevADHRRxC95P0v2zsAB3R2cQHxxaO+inyKtiZbDC/YsoRV4iHzrEhhbCLK/9jLWp4jQkWI7ZxQh3UHPraWTeZ6I8cKK50g6v5g=
    - secure: abSaGnArhFLAMbop5WKMef+IuDP49HliznG8LIM/PTuyfSg/VzF+qGszmoi/QVREdSQly3epVOCB/sB0QWY+ntjWkkBB5VPNlIYudZECkIGAv9V5BUVQa/aubU79l6AVvyEaTTdnXDN6ny9/xGEYEKUSHUdQwM2RjacuhyeOuLHW5Ir59UuoTqjpbRHpvnz84HWHhw71/jUsKIcO5CtJrUQwKhHhr+oOkQYSKxG8nxVIl8KLfO8ouU1PU3W2OxIlDSx/2aiwCynUVt60megKExKSALYGFVpcxO2GdaQ4nDOCnk1OwUta8GCXCe7vwH/BUdeY4BF96nadd6TqYcz2GofcYbOxLviHJd85k+paS7E4cBLmbwh4gXedzgnLhOtLoZBtDfqGUBOdgeQe6nIq6uRsl4HMPkqh3i4rUPdekuCeDacSKoTATIhRB5zUKf/ESFTj+mUDiDGhLXan5pRusMXltIkZ4bj7CFrfbw1W4pU9tux9TU60hsXckGhqUw7koyFPE24jND5HGkKR4bs2/eHM5Lx5iWUfL3I3oGKt+gjItHVuSq7kiJT3PEUB7jXYwmsyLh7xiGTZdMVtNwssghR/yQl4jPpkD/WZ9bSrGHod6ib0dkXGBLRZQ8BF49Mf3AgdRKKMGufSoS/2POqMaVt7Sei/9KEe3Ujd+fjxY7Q=
```
